services:
  gateway:
    build: .
    working_dir: /app/gateway
    command: npm run watch
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      HTTP_PORT: 3000
      WS_PORT: 8080
      REPLICA_URLS: http://replica1:5001,http://replica2:5002,http://replica3:5003,http://replica4:5004
    volumes:
      - ./gateway:/app/gateway
    depends_on:
      replica1:
        condition: service_started
      replica2:
        condition: service_started
      replica3:
        condition: service_started
      replica4:
        condition: service_started

  replica1:
    build: .
    working_dir: /app/replica
    command: npm run watch:r1
    ports:
      - "5001:5001"
    environment:
      NODE_ID: replica1
      PORT: 5001
      PEERS: http://replica2:5002,http://replica3:5003,http://replica4:5004
      GATEWAY_URL: http://gateway:3000
    volumes:
      - ./replica:/app/replica

  replica2:
    build: .
    working_dir: /app/replica
    command: npm run watch:r2
    ports:
      - "5002:5002"
    environment:
      NODE_ID: replica2
      PORT: 5002
      PEERS: http://replica1:5001,http://replica3:5003,http://replica4:5004
      GATEWAY_URL: http://gateway:3000
    volumes:
      - ./replica:/app/replica

  replica3:
    build: .
    working_dir: /app/replica
    command: npm run watch:r3
    ports:
      - "5003:5003"
    environment:
      NODE_ID: replica3
      PORT: 5003
      PEERS: http://replica1:5001,http://replica2:5002,http://replica4:5004
      GATEWAY_URL: http://gateway:3000
    volumes:
      - ./replica:/app/replica

  replica4:
    build: .
    working_dir: /app/replica
    command: npm run watch:r4
    ports:
      - "5004:5004"
    environment:
      NODE_ID: replica4
      PORT: 5004
      PEERS: http://replica1:5001,http://replica2:5002,http://replica3:5003
      GATEWAY_URL: http://gateway:3000
    volumes:
      - ./replica:/app/replica
